### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by ghost** [andreicristianpetcu/NewTab2about-home#1]
Just wanted to add a Chinese Translation, sorry for the lack of a patch.

The description should be "把新标签页替代about:home页。“

The addon name should be ”新标签页到about:home页“

Might as well add the Taiwanese translation as well.

description: “把新標籤頁替代about:home頁。“

Title: ”新標籤頁到about:home頁“

Thanks

**Comment by andreicristianpetcu** [comment]
I would accept such a pull request. I never i18n-ed a WebExtension (I'm pretty new to building WebExtensions :D ). I see that [this show how you can do such a task](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization).

**Comment by andreicristianpetcu** [comment]
It will arrive in a future update :) @chinaar

**Comment by andreicristianpetcu** [comment]
@chinaar the translations landed in AMO. Please update :D You should see version 1.2.0
